server:
  port: 8086

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: QUIZ-SERVICE
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/quiz/**, /quiz-test/**
        - id: QUESTION-service
          uri: lb://QUESTION-SERVICE
          predicates:
            - Path=/question/**
        - id: MOVIE-CATALOG-SERVICE
          uri: lb://MOVIE-CATALOG-SERVICE
          predicates:
            - Path=/catalog/**,

# Replace quiz-service and question-service with your actual service names
